export enum RELICS_NAME {
  HEAL = "HEAL",
  IMMUNITY = "IMMUNITY",
  REGENERATION = "REGENERATION",
  POISON_CURE = "POISON_CURE",
  FEAR = "FEAR",
  NIGHT_VISION = "NIGHT_VISION",
  PORTAL = "PORTAL",
  BERSERK = "BERSERK",
  GUARDIAN_ANGEL = "GUARDIAN_ANGEL",
  STABILIZER = "STABILIZER",
}
